import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { Signika } from "next/font/google";

const signika = Signika({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Super Food",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const categoriesList = await getData("product/categories");

  return (
    <html lang="en">
      <body className={`${signika.className}`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
